#!/usr/bin/env python

import glob, os, sys, subprocess, shutil, string, argparse

parser = argparse.ArgumentParser(description="Wrapper script for testGFW2Tool. This gets called on the PBS worker node via the PBS script generated by submit-PBS-ARRAY-ttHMultiGFW2.py. The sample to be processed gets retrieved via the PBS_ARRAYID index.")

parser.add_argument("--inputpath", dest="inputpath", action="store", type=str)
parser.add_argument("--outputpath", dest="outputpath", action="store", type=str)
parser.add_argument("--samplelist", dest="samplelist", action="store", type=str, nargs="+")
parser.add_argument("--config", dest="config", action="store", default=None, type=str)
parser.add_argument("--nevents", dest="nevents", action="store", default="0", type=str)

args = parser.parse_args()

if __name__ == '__main__':

    # Read samplelist from argparse.
    # It will automagically re-create a python list from the multiple arguments of the input --samplelist option.

    samplelist = args.samplelist

    # Get the sample from the PBS_ARRAYID

    pbs_array_idx = int(os.getenv('PBS_ARRAYID'))

    sample = samplelist[pbs_array_idx]

    print("Current job index PBS_ARRAYID={0}, sample={1}".format(pbs_array_idx,sample))

    if sample[0:2] == "00":
        append = "Data"
    else:
        #append = "Nominal"
        append = "Nominal_PLICFT"
        #append = "ttbar_ttgamma/Nominal"

    infile    =  args.inputpath + "/" + append + "/" + sample + "/" + sample + ".root"
    submitdir = sample

    rootcoredir = os.getenv('PWD') + "/RootCoreBin/bin/x86_64-slc6-gcc49-opt/"

    config   = args.config
    nevents  = args.nevents
    outputpath  = args.outputpath

    # OK, execute testGFW2Tool for this sample!

    # Clear the cache w/ this dummy shell operation (Sean's suggestion)
    subprocess.call(["ls", "-l","/coepp/cephfs/mel/mmilesi"])

    cmd = "testGFW2Tool --sp {0} --conf {1} --me {2}".format(infile,config,nevents)

    print("Executing command:\n{0}".format(cmd))

    subprocess.call( cmd, shell=True )

    if not os.path.exists(outputpath):
        os.makedirs(outputpath)

    cmd_copy = "rsync -azP *.root {0}/".format(outputpath)

    print("Copying output:\n{0}".format(cmd_copy))

    # Sean changing this to popen to get output
    copyproc = subprocess.Popen(cmd_copy,shell=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
    out,err = copyproc.communicate()
    print out,err

